name: "♻️ Refactoring"
description: "Code changes that neither fix a bug nor add a feature."
labels: ["refactor"]
body:
  - type: textarea
    id: scope
    attributes:
      label: "Refactoring Scope"
      description: "Which part of the codebase is being improved?"
  - type: textarea
    id: reason
    attributes:
      label: "Reason for Refactoring"
      description: "Why is this change necessary? (e.g., readability, performance)"
